/**
 * Codex OS Boot Manager v2
 * Unified Service Registry
 */

export interface ManagedService {
  name: string;
  cwd: string;
  startCommand: string;
  port: number;
  healthUrl: string;
  required: boolean;
  group: "core" | "execution" | "ai" | "safety" | "optimization" | "identity" | "infra";
}

export const SERVICES_V2: ManagedService[] = [
  // ========== CORE GROUP (3 services) ==========
  {
    name: "Brain v2",
    cwd: "../codex-brain",
    startCommand: "npm start",
    port: 4100,
    healthUrl: "http://localhost:4100/v2/health",
    required: true,
    group: "core",
  },
  {
    name: "Bridge",
    cwd: "../codex-bridge",
    startCommand: "npm start",
    port: 4000,
    healthUrl: "http://localhost:4000/health",
    required: true,
    group: "core",
  },
  {
    name: "Orchestrator",
    cwd: "../codex-orchestrator",
    startCommand: "npm start",
    port: 4200,
    healthUrl: "http://localhost:4200/health",
    required: true,
    group: "core",
  },

  // ========== EXECUTION GROUP (10 services) ==========
  {
    name: "Hands v5",
    cwd: "../codex-hands",
    startCommand: "npm start",
    port: 4300,
    healthUrl: "http://localhost:4300/hands/health",
    required: true,
    group: "execution",
  },
  {
    name: "Video Engine",
    cwd: "../codex-video",
    startCommand: "npm start",
    port: 4700,
    healthUrl: "http://localhost:4700/health",
    required: true,
    group: "execution",
  },
  {
    name: "Vision v3",
    cwd: "../codex-vision-2.6",
    startCommand: "npm start",
    port: 4650,
    healthUrl: "http://localhost:4650/health",
    required: true,
    group: "execution",
  },
  {
    name: "Social Engine",
    cwd: "../codex-social",
    startCommand: "npm start",
    port: 4800,
    healthUrl: "http://localhost:4800/health",
    required: true,
    group: "execution",
  },
  {
    name: "Creative Suite",
    cwd: "../codex-creative-suite",
    startCommand: "npm start",
    port: 5250,
    healthUrl: "http://localhost:5250/health",
    required: true,
    group: "execution",
  },
  {
    name: "Campaign",
    cwd: "../codex-campaign",
    startCommand: "npm start",
    port: 5120,
    healthUrl: "http://localhost:5120/health",
    required: true,
    group: "execution",
  },
  {
    name: "E-Commerce",
    cwd: "../codex-ecommerce",
    startCommand: "npm start",
    port: 5100,
    healthUrl: "http://localhost:5100/health",
    required: true,
    group: "execution",
  },
  {
    name: "Distribution v2",
    cwd: "../codex-distribution-v2",
    startCommand: "npm start",
    port: 5301,
    healthUrl: "http://localhost:5301/health",
    required: true,
    group: "execution",
  },
  {
    name: "Routing v2",
    cwd: "../codex-routing-v2",
    startCommand: "npm start",
    port: 5560,
    healthUrl: "http://localhost:5560/health",
    required: true,
    group: "execution",
  },
  {
    name: "Monetization",
    cwd: "../codex-monetization",
    startCommand: "npm start",
    port: 4850,
    healthUrl: "http://localhost:4850/health",
    required: false,
    group: "execution",
  },

  // ========== AI GROUP (7 services) ==========
  {
    name: "Knowledge",
    cwd: "../codex-knowledge-v2",
    startCommand: "npm start",
    port: 4500,
    healthUrl: "http://localhost:4500/health",
    required: false,
    group: "ai",
  },
  {
    name: "Strategy",
    cwd: "../codex-strategy",
    startCommand: "npm start",
    port: 5050,
    healthUrl: "http://localhost:5050/health",
    required: false,
    group: "ai",
  },
  {
    name: "Trends",
    cwd: "../codex-trends",
    startCommand: "npm start",
    port: 5230,
    healthUrl: "http://localhost:5230/health",
    required: false,
    group: "ai",
  },
  {
    name: "Simulation",
    cwd: "../codex-sim",
    startCommand: "npm start",
    port: 5070,
    healthUrl: "http://localhost:5070/health",
    required: false,
    group: "ai",
  },
  {
    name: "Adaptive Intelligence",
    cwd: "../codex-adaptive",
    startCommand: "npm start",
    port: 5440,
    healthUrl: "http://localhost:5440/health",
    required: false,
    group: "ai",
  },
  {
    name: "Adaptive Strategy",
    cwd: "../codex-adaptive-strategy",
    startCommand: "npm start",
    port: 5445,
    healthUrl: "http://localhost:5445/health",
    required: false,
    group: "ai",
  },
  {
    name: "Meta-Cognition",
    cwd: "../codex-metacog",
    startCommand: "npm start",
    port: 5580,
    healthUrl: "http://localhost:5580/health",
    required: false,
    group: "ai",
  },

  // ========== SAFETY GROUP (8 services) ==========
  {
    name: "Self-Audit",
    cwd: "../codex-self-audit",
    startCommand: "npm start",
    port: 5530,
    healthUrl: "http://localhost:5530/health",
    required: true,
    group: "safety",
  },
  {
    name: "SRL",
    cwd: "../codex-srl",
    startCommand: "npm start",
    port: 5540,
    healthUrl: "http://localhost:5540/health",
    required: true,
    group: "safety",
  },
  {
    name: "Hardening",
    cwd: "../codex-hardening",
    startCommand: "npm start",
    port: 5555,
    healthUrl: "http://localhost:5555/health",
    required: true,
    group: "safety",
  },
  {
    name: "Mesh",
    cwd: "../codex-mesh",
    startCommand: "npm start",
    port: 5565,
    healthUrl: "http://localhost:5565/health",
    required: true,
    group: "safety",
  },
  {
    name: "Autonomy Engine",
    cwd: "../codex-autonomy",
    startCommand: "npm start",
    port: 5420,
    healthUrl: "http://localhost:5420/health",
    required: true,
    group: "safety",
  },
  {
    name: "Autonomy Workflow",
    cwd: "../codex-autonomy-workflows",
    startCommand: "npm start",
    port: 5430,
    healthUrl: "http://localhost:5430/health",
    required: true,
    group: "safety",
  },
  {
    name: "Autonomy Memory",
    cwd: "../codex-autonomy-memory",
    startCommand: "npm start",
    port: 5570,
    healthUrl: "http://localhost:5570/health",
    required: false,
    group: "safety",
  },
  {
    name: "Account Safety",
    cwd: "../codex-accounts",
    startCommand: "npm start",
    port: 5090,
    healthUrl: "http://localhost:5090/health",
    required: false,
    group: "safety",
  },

  // ========== OPTIMIZATION GROUP (4 services) ==========
  {
    name: "Performance Refinement",
    cwd: "../codex-performance-refinement",
    startCommand: "npm start",
    port: 5520,
    healthUrl: "http://localhost:5520/health",
    required: false,
    group: "optimization",
  },
  {
    name: "Optimizer",
    cwd: "../codex-optimizer",
    startCommand: "npm start",
    port: 5490,
    healthUrl: "http://localhost:5490/health",
    required: false,
    group: "optimization",
  },
  {
    name: "CrossVal",
    cwd: "../codex-crossval",
    startCommand: "npm start",
    port: 5470,
    healthUrl: "http://localhost:5470/health",
    required: false,
    group: "optimization",
  },
  {
    name: "RL",
    cwd: "../codex-rl",
    startCommand: "npm start",
    port: 5495,
    healthUrl: "http://localhost:5495/health",
    required: false,
    group: "optimization",
  },

  // ========== IDENTITY GROUP (4 services) ==========
  {
    name: "Profiles",
    cwd: "../codex-profiles",
    startCommand: "npm start",
    port: 5180,
    healthUrl: "http://localhost:5180/health",
    required: true,
    group: "identity",
  },
  {
    name: "Identity",
    cwd: "../codex-identity",
    startCommand: "npm start",
    port: 5185,
    healthUrl: "http://localhost:5185/health",
    required: true,
    group: "identity",
  },
  {
    name: "Vault",
    cwd: "../codex-vault",
    startCommand: "npm start",
    port: 5175,
    healthUrl: "http://localhost:5175/health",
    required: true,
    group: "identity",
  },
  {
    name: "Domain",
    cwd: "../codex-domain",
    startCommand: "npm start",
    port: 5160,
    healthUrl: "http://localhost:5160/health",
    required: true,
    group: "identity",
  },

  // ========== INFRA GROUP (6 services) ==========
  {
    name: "Ops",
    cwd: "../codex-ops",
    startCommand: "npm start",
    port: 5350,
    healthUrl: "http://localhost:5350/ops/health",
    required: false,
    group: "infra",
  },
  {
    name: "Telemetry",
    cwd: "../codex-telemetry",
    startCommand: "npm start",
    port: 4950,
    healthUrl: "http://localhost:4950/health",
    required: false,
    group: "infra",
  },
  {
    name: "Stability",
    cwd: "../codex-stability",
    startCommand: "npm start",
    port: 4850,
    healthUrl: "http://localhost:4850/health",
    required: false,
    group: "infra",
  },
  {
    name: "Visibility",
    cwd: "../codex-visibility",
    startCommand: "npm start",
    port: 5200,
    healthUrl: "http://localhost:5200/health",
    required: false,
    group: "infra",
  },
  {
    name: "Engagement",
    cwd: "../codex-engagement",
    startCommand: "npm start",
    port: 5210,
    healthUrl: "http://localhost:5210/health",
    required: false,
    group: "infra",
  },
  {
    name: "Voice v2",
    cwd: "../codex-voice",
    startCommand: "npm start",
    port: 9000,
    healthUrl: "http://localhost:9000/health",
    required: false,
    group: "infra",
  },
];
